//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "circle")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub works: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    pub url: Time,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::circle_to_meta::Entity")]
    CircleToMeta,
}

impl Related<super::circle_to_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CircleToMeta.def()
    }
}

impl Related<super::meta::Entity> for Entity {
    fn to() -> RelationDef {
        super::circle_to_meta::Relation::Meta.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::circle_to_meta::Relation::Circle.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
