//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "illust_to_meta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub illust_id: i32,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub meta_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::illust::Entity",
        from = "Column::IllustId",
        to = "super::illust::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Illust,
    #[sea_orm(
        belongs_to = "super::meta::Entity",
        from = "Column::MetaId",
        to = "super::meta::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Meta,
}

impl Related<super::illust::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Illust.def()
    }
}

impl Related<super::meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meta.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
