//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "meta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub img_src: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    #[sea_orm(column_type = "Text")]
    pub file_path: String,
    pub time: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::circle_to_meta::Entity")]
    CircleToMeta,
    #[sea_orm(has_many = "super::cv_to_meta::Entity")]
    CvToMeta,
    #[sea_orm(has_many = "super::genre_to_meta::Entity")]
    GenreToMeta,
    #[sea_orm(has_many = "super::illust_to_meta::Entity")]
    IllustToMeta,
    #[sea_orm(has_many = "super::scenario_to_meta::Entity")]
    ScenarioToMeta,
    #[sea_orm(has_many = "super::time_table_to_meta::Entity")]
    TimeTableToMeta,
}

impl Related<super::circle_to_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CircleToMeta.def()
    }
}

impl Related<super::cv_to_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CvToMeta.def()
    }
}

impl Related<super::genre_to_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GenreToMeta.def()
    }
}

impl Related<super::illust_to_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IllustToMeta.def()
    }
}

impl Related<super::scenario_to_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScenarioToMeta.def()
    }
}

impl Related<super::time_table_to_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimeTableToMeta.def()
    }
}

impl Related<super::circle::Entity> for Entity {
    fn to() -> RelationDef {
        super::circle_to_meta::Relation::Circle.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::circle_to_meta::Relation::Meta.def().rev())
    }
}

impl Related<super::cv::Entity> for Entity {
    fn to() -> RelationDef {
        super::cv_to_meta::Relation::Cv.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::cv_to_meta::Relation::Meta.def().rev())
    }
}

impl Related<super::genre::Entity> for Entity {
    fn to() -> RelationDef {
        super::genre_to_meta::Relation::Genre.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::genre_to_meta::Relation::Meta.def().rev())
    }
}

impl Related<super::illust::Entity> for Entity {
    fn to() -> RelationDef {
        super::illust_to_meta::Relation::Illust.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::illust_to_meta::Relation::Meta.def().rev())
    }
}

impl Related<super::scenario::Entity> for Entity {
    fn to() -> RelationDef {
        super::scenario_to_meta::Relation::Scenario.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::scenario_to_meta::Relation::Meta.def().rev())
    }
}

impl Related<super::time_table::Entity> for Entity {
    fn to() -> RelationDef {
        super::time_table_to_meta::Relation::TimeTable.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::time_table_to_meta::Relation::Meta.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
