//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub mod prelude;

pub mod circle;
pub mod circle_to_meta;
pub mod cv;
pub mod cv_to_meta;
pub mod genre;
pub mod genre_to_meta;
pub mod illust;
pub mod illust_to_meta;
pub mod meta;
pub mod scenario;
pub mod scenario_to_meta;
pub mod time_table;
pub mod time_table_to_meta;
