//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "time_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub index: i32,
    #[sea_orm(column_type = "Text")]
    pub time: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::time_table_to_meta::Entity")]
    TimeTableToMeta,
}

impl Related<super::time_table_to_meta::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TimeTableToMeta.def()
    }
}

impl Related<super::meta::Entity> for Entity {
    fn to() -> RelationDef {
        super::time_table_to_meta::Relation::Meta.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::time_table_to_meta::Relation::TimeTable.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
